services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mdd-db'
    restart: 'always'
    environment:
      - 'MYSQL_DATABASE=mdd'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3307:3306'
    volumes:
      - 'mdd-db:/var/lib/mysql'

volumes:
    mdd-db:
      driver: local
